version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  build:
    docker:
      - image: cimg/node:16.16
    steps:
      - checkout
      - node/install-packages:
          "npm i"
      - run:
          name: Run tests
          command: npm test

workflows:
  main:
    jobs:
      - build
      
 